name: QuickDine CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Build project
        run: mvn clean install -DskipTests
               
               - name: Install ChromeDriver
               run: |
                 sudo apt-get update
                 sudo apt-get install -y chromium-chromedriver
                 sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Check Chrome & ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run unit tests
        run: mvn test -Dtest=!ReservationUITest

      - name: Start backend
        run: mvn spring-boot:run &

      - name: Run Selenium UI tests
        run: mvn test -Dtest=ReservationUITest
